name: CI / CD
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  packages: write

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go mod download -x
      - run: go test -v ./...
  e2e:
    name: E2E (${{ matrix.label }})
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        include:
          - label: dynamodb-local
            image: amazon/dynamodb-local
            container-port: 8000
          - label: ministack
            image: ministackorg/ministack
            container-port: 4566
    services:
      backend:
        image: ${{ matrix.image }}
        ports:
          - 8000:${{ matrix.container-port }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go mod download -x
      - run: go build -o ./dynamodb-local-proxy .
      - run: ./dynamodb-local-proxy > out.log 2>&1 &
        env:
          LOG_LEVEL: DEBUG
      - uses: hashicorp/setup-terraform@v4
      - run: terraform init
        working-directory: e2e
      - run: terraform plan
        timeout-minutes: 1
        working-directory: e2e
      - run: terraform apply -auto-approve
        working-directory: e2e
        timeout-minutes: 3
      - run: cat out.log
        if: always()
  ci-passed:
    name: CI passed
    runs-on: ubuntu-24.04-arm
    needs: [test, e2e]
    steps:
      - run: echo OK
  build-and-push:
    name: CD
    runs-on: ubuntu-24.04-arm
    needs: [ci-passed]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/utgwkk/dynamodb-local-proxy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
      - uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=linux/amd64
            type=gha,scope=linux/arm64
          cache-to: |
            type=gha,mode=max,scope=linux/amd64
            type=gha,mode=max,scope=linux/arm64
